--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 10 2018 22:41
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'ZipListe'   
-- ZipListID       :  
-- ZipCode         :  
--
CREATE TABLE ZipListe (
    ZipListID      BIGINT IDENTITY(1,1) NOT NULL,
    ZipCode        BIGINT NOT NULL,
CONSTRAINT pk_ZipListe PRIMARY KEY CLUSTERED (ZipListID))